import Head from 'next/head';
// import Home from '../components/Home/Home';
import Footer from '../components/Layout/Footer/Footer';
import HomePage from '../components/HomePage/HomePage';

// import Home from '../components/Home/HomePage';

import classes from '../styles/index.module.scss';

export default function Home() {
	return (
		<div className={classes.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={classes.main}>
				<HomePage />
			</main>
		</div>
	);
}
